### ISSUE TITLE
Update the blog Page

### ISSUE THREAD

**Issue by CoderSaty** [CoderSaty/LevelZeroPortfolio#24]
Make a new card for the blogs on the blog page similar to the project page.

**Comment by rohitdubey1352** [comment]
Then, what should we add to cards? In Blog Page.

**Comment by Gourav-Kr** [comment]
Sir May I work on this issue?

**Comment by rohitdubey1352** [comment]
Sure

**Comment by rohitdubey1352** [comment]
I have already done with that, have a look and tell me if u need anything to change in that.
Check on the Blog Page and I have aligned all the items.
https://rohitdubey1352.github.io/LevelZeroPortfolio/
