### ISSUE TITLE
To add icons of linkedin, twitter and github.

### ISSUE THREAD

**Issue by ishika1661** [CoderSaty/LevelZeroPortfolio#3]
I would like to do this.

**Comment by ishika1661** [comment]
Thanks. I will do it.

**Comment by saraswatrupendra** [comment]
I like to do this can you please assign this to me

**Comment by CoderSaty** [comment]
@ishika1661 are you still willing to do this or should I assign it to @saraswatrupendra ?

**Comment by gulshanjakhon** [comment]
Assign Me to please

**Comment by ishika1661** [comment]
Sorry something important came up and I am no longer participating in
hacktoberfest. You can assign this issue to others.
Thank you.

**Comment by CoderSaty** [comment]
> Assign Me to please

@gulshanjakhon you can go ahead.
